# Generated by Django 4.2.7 on 2025-08-13 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(max_length=20, verbose_name="شماره کارت"),
                ),
                (
                    "card_holder",
                    models.CharField(max_length=100, verbose_name="نام صاحب کارت"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "کارت پرداخت",
                "verbose_name_plural": "کارت\u200cهای پرداخت",
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("waiting_approval", "در انتظار تایید"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                            ("expired", "منقضی شده"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(default=uuid.uuid4, max_length=100, unique=True),
                ),
                (
                    "payment_receipt",
                    models.ImageField(blank=True, null=True, upload_to="receipts/"),
                ),
                ("vpn_config", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "خرید",
                "verbose_name_plural": "خریدها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VPNPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام پلن")),
                (
                    "duration_days",
                    models.IntegerField(
                        choices=[
                            (30, "1 ماه"),
                            (90, "3 ماه"),
                            (180, "6 ماه"),
                            (365, "1 سال"),
                        ],
                        verbose_name="مدت زمان",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="قیمت (تومان)"
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "پلن VPN",
                "verbose_name_plural": "پلن\u200cهای VPN",
            },
        ),
        migrations.RemoveField(
            model_name="vpnaccount",
            name="order",
        ),
        migrations.RemoveField(
            model_name="vpnaccount",
            name="user",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Plan",
        ),
        migrations.DeleteModel(
            name="VPNAccount",
        ),
        migrations.AddField(
            model_name="purchase",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.vpnplan"
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
